# Challenge

Write code that reads the JSONL files from the CLOY data folder and creates dataframe (indexed by datetime, similar to Week 3). Then, using timeseries operations in pandas generate a graph for showing the number of posts / comments over time (daily, weekly, monthly).

This is my pseudocode that I wrote out:

1. Read JSONL
2. For every line, call json.loads to save as a separate object (Create an updating dictionary, Extract the created_utc value and convert it to a datetime object - should it be timezone aware? If timestamp is new, create new key and increment value by 1; if timestamp is not new, update the original value corresponding to the key by adding 1 
3. We have one dictionary for comments and one dictionary for submissions   

4. Create DFs: Turn dictionaries into dfs and read the keys as index, rename the column as count   
a. Plot by day (X axis = years, Y axis = count; Don’t need to group by but just a line plot connecting each day).  
b. Plot by week / year.   
Resampling (I had to look this up): weekly_df = daily_df.resample('W').sum(), or yearly_df = daily_df.resample(“YE”).sum()

**NOTE**: I asked Han if i should try to take the timezones into account and I agree that as long as the time is consistent within the dataset, it should be fine.

In [1]:
import json

Let's first figure out how to convert an integer to a datetime object.

In [10]:
from datetime import datetime
timestamp = 1583764623
dt_utc = datetime.fromtimestamp(timestamp)
dt_utc

datetime.datetime(2020, 3, 9, 10, 37, 3)

In [14]:
dt_utc.date()
# making a fake dictionary

dct = {}
dct[dt_utc] = 3

dct

{datetime.datetime(2020, 3, 9, 10, 37, 3): 3}

Can we make this into a DF?

In [ ]:
import pandas as pd
df = pd.DataFrame.from_dict(dct, orient='index') # i got this line from online
df

                     0
2020-03-09 10:37:03  3

Maybe we don't want the exact times...? So should we just extract .day() like:

In [19]:
dct = {}
dct[dt_utc.date()] = 3
df = pd.DataFrame.from_dict(dct, orient='index') # i got this line from online
df

            0
2020-03-09  3

Let's start by reading just one cloy_comments_2020.jsonl.

In [ ]:
temp_counts = {}
with open ('/Users/crystalzhao/Desktop/~WELLESLEY~/FALL_26/CS 315/week4-tasks-new/data/CLOY/cloy_comments_2020.jsonl', 'r', encoding = 'utf-8') as f:
    for line in f:
        data = json.loads(line) # to make sure each json line is handled as a vector
        utc = data['created_utc']
        dt_utc = datetime.fromtimestamp(utc).date()
        temp_counts[dt_utc] = temp_counts.get(dt_utc, 0) + 1   # this checks if the key exists and returns 0 if missing, then add one

In [21]:
temp_counts

{datetime.date(2020, 3, 9): 2,
 datetime.date(2020, 3, 10): 1,
 datetime.date(2020, 3, 11): 4,
 datetime.date(2020, 3, 12): 1,
 datetime.date(2020, 3, 13): 1,
 datetime.date(2020, 3, 14): 1,
 datetime.date(2020, 3, 15): 2,
 datetime.date(2020, 3, 16): 5,
 datetime.date(2020, 3, 17): 4,
 datetime.date(2020, 3, 18): 13,
 datetime.date(2020, 3, 19): 13,
 datetime.date(2020, 3, 20): 2,
 datetime.date(2020, 3, 21): 1,
 datetime.date(2020, 3, 22): 3,
 datetime.date(2020, 3, 23): 1,
 datetime.date(2020, 3, 24): 2,
 datetime.date(2020, 3, 25): 6,
 datetime.date(2020, 3, 26): 6,
 datetime.date(2020, 3, 27): 6,
 datetime.date(2020, 3, 28): 5,
 datetime.date(2020, 3, 29): 5,
 datetime.date(2020, 3, 30): 18,
 datetime.date(2020, 3, 31): 14,
 datetime.date(2020, 4, 1): 23,
 datetime.date(2020, 4, 2): 5,
 datetime.date(2020, 4, 3): 1,
 datetime.date(2020, 4, 4): 4,
 datetime.date(2020, 4, 5): 4,
 datetime.date(2020, 4, 6): 5,
 datetime.date(2020, 4, 7): 2,
 datetime.date(2020, 4, 8): 2,
 datetime.date(2020, 4, 9): 6,
 datetime.date(2020, 4, 10): 4,
 datetime.date(2020, 4, 11): 10,
 datetime.date(2020, 4, 12): 2,
 datetime.date(2020, 4, 13): 12,
 datetime.date(2020, 4, 14): 11,
 datetime.date(2020, 4, 15): 5,
 datetime.date(2020, 4, 16): 35,
 datetime.date(2020, 4, 17): 3,
 datetime.date(2020, 4, 18): 20,
 datetime.date(2020, 4, 19): 11,
 datetime.date(2020, 4, 20): 2,
 datetime.date(2020, 4, 21): 1,
 datetime.date(2020, 4, 22): 12,
 datetime.date(2020, 4, 23): 5,
 datetime.date(2020, 4, 24): 7,
 datetime.date(2020, 4, 25): 6,
 datetime.date(2020, 4, 26): 28,
 datetime.date(2020, 4, 27): 41,
 datetime.date(2020, 4, 28): 17,
 datetime.date(2020, 4, 29): 9,
 datetime.date(2020, 4, 30): 28,
 datetime.date(2020, 5, 1): 8,
 datetime.date(2020, 5, 2): 5,
 datetime.date(2020, 5, 3): 5,
 datetime.date(2020, 5, 4): 20,
 datetime.date(2020, 5, 5): 16,
 datetime.date(2020, 5, 6): 12,
 datetime.date(2020, 5, 7): 12,
 datetime.date(2020, 5, 8): 11,
 datetime.date(2020, 5, 9): 16,
 datetime.date(2020, 5, 10): 58,
 datetime.date(2020, 5, 11): 32,
 datetime.date(2020, 5, 12): 36,
 datetime.date(2020, 5, 13): 27,
 datetime.date(2020, 5, 14): 39,
 datetime.date(2020, 5, 15): 25,
 datetime.date(2020, 5, 16): 34,
 datetime.date(2020, 5, 17): 37,
 datetime.date(2020, 5, 18): 47,
 datetime.date(2020, 5, 19): 33,
 datetime.date(2020, 5, 20): 67,
 datetime.date(2020, 5, 21): 23,
 datetime.date(2020, 5, 22): 33,
 datetime.date(2020, 5, 23): 23,
 datetime.date(2020, 5, 24): 20,
 datetime.date(2020, 5, 25): 35,
 datetime.date(2020, 5, 26): 22,
 datetime.date(2020, 5, 27): 18,
 datetime.date(2020, 5, 28): 24,
 datetime.date(2020, 5, 29): 15,
 datetime.date(2020, 5, 30): 21,
 datetime.date(2020, 5, 31): 28,
 datetime.date(2020, 6, 1): 11,
 datetime.date(2020, 6, 2): 34,
 datetime.date(2020, 6, 3): 15,
 datetime.date(2020, 6, 4): 32,
 datetime.date(2020, 6, 5): 77,
 datetime.date(2020, 6, 6): 14,
 datetime.date(2020, 6, 7): 70,
 datetime.date(2020, 6, 8): 40,
 datetime.date(2020, 6, 9): 32,
 datetime.date(2020, 6, 10): 33,
 datetime.date(2020, 6, 11): 31,
 datetime.date(2020, 6, 12): 27,
 datetime.date(2020, 6, 13): 61,
 datetime.date(2020, 6, 14): 40,
 datetime.date(2020, 6, 15): 28,
 datetime.date(2020, 6, 16): 38,
 datetime.date(2020, 6, 17): 29,
 datetime.date(2020, 6, 18): 37,
 datetime.date(2020, 6, 19): 48,
 datetime.date(2020, 6, 20): 19,
 datetime.date(2020, 6, 21): 36,
 datetime.date(2020, 6, 22): 23,
 datetime.date(2020, 6, 23): 25,
 datetime.date(2020, 6, 24): 19,
 datetime.date(2020, 6, 25): 21,
 datetime.date(2020, 6, 26): 16,
 datetime.date(2020, 6, 27): 16,
 datetime.date(2020, 6, 28): 15,
 datetime.date(2020, 6, 29): 22,
 datetime.date(2020, 6, 30): 19,
 datetime.date(2020, 7, 1): 28,
 datetime.date(2020, 7, 2): 11,
 datetime.date(2020, 7, 3): 42,
 datetime.date(2020, 7, 4): 26,
 datetime.date(2020, 7, 5): 35,
 datetime.date(2020, 7, 6): 35,
 datetime.date(2020, 7, 7): 21,
 datetime.date(2020, 7, 8): 16,
 datetime.date(2020, 7, 9): 21,
 datetime.date(2020, 7, 10): 15,
 datetime.date(2020, 7, 11): 66,
 datetime.date(2020, 7, 12): 36,
 datetime.date(2020, 7, 13): 17,
 datetime.date(2020, 7, 14): 29,
 datetime.date(2020, 7, 15): 15,
 datetime.date(2020, 7, 16): 14,
 datetime.date(2020, 7, 17): 4,
 datetime.date(2020, 7, 18): 7,
 datetime.date(2020, 7, 19): 12,
 datetime.date(2020, 7, 20): 22,
 datetime.date(2020, 7, 21): 1,
 datetime.date(2020, 7, 22): 27,
 datetime.date(2020, 7, 23): 47,
 datetime.date(2020, 7, 24): 43,
 datetime.date(2020, 7, 25): 28,
 datetime.date(2020, 7, 26): 20,
 datetime.date(2020, 7, 27): 21,
 datetime.date(2020, 7, 28): 14,
 datetime.date(2020, 7, 29): 42,
 datetime.date(2020, 7, 30): 58,
 datetime.date(2020, 7, 31): 13,
 datetime.date(2020, 8, 1): 17,
 datetime.date(2020, 8, 2): 69,
 datetime.date(2020, 8, 3): 53,
 datetime.date(2020, 8, 4): 71,
 datetime.date(2020, 8, 5): 79,
 datetime.date(2020, 8, 6): 50,
 datetime.date(2020, 8, 7): 32,
 datetime.date(2020, 8, 8): 4,
 datetime.date(2020, 8, 9): 10,
 datetime.date(2020, 8, 10): 29,
 datetime.date(2020, 8, 11): 36,
 datetime.date(2020, 8, 12): 51,
 datetime.date(2020, 8, 13): 32,
 datetime.date(2020, 8, 14): 17,
 datetime.date(2020, 8, 15): 11,
 datetime.date(2020, 8, 16): 7,
 datetime.date(2020, 8, 17): 27,
 datetime.date(2020, 8, 18): 39,
 datetime.date(2020, 8, 19): 12,
 datetime.date(2020, 8, 20): 16,
 datetime.date(2020, 8, 21): 8,
 datetime.date(2020, 8, 22): 17,
 datetime.date(2020, 8, 23): 47,
 datetime.date(2020, 8, 24): 22,
 datetime.date(2020, 8, 25): 7,
 datetime.date(2020, 8, 26): 26,
 datetime.date(2020, 8, 27): 42,
 datetime.date(2020, 8, 28): 33,
 datetime.date(2020, 8, 29): 29,
 datetime.date(2020, 8, 30): 48,
 datetime.date(2020, 8, 31): 47,
 datetime.date(2020, 9, 1): 46,
 datetime.date(2020, 9, 2): 13,
 datetime.date(2020, 9, 3): 37,
 datetime.date(2020, 9, 4): 20,
 datetime.date(2020, 9, 5): 19,
 datetime.date(2020, 9, 6): 14,
 datetime.date(2020, 9, 7): 12,
 datetime.date(2020, 9, 8): 32,
 datetime.date(2020, 9, 9): 53,
 datetime.date(2020, 9, 10): 62,
 datetime.date(2020, 9, 11): 32,
 datetime.date(2020, 9, 12): 29,
 datetime.date(2020, 9, 13): 41,
 datetime.date(2020, 9, 14): 58,
 datetime.date(2020, 9, 15): 29,
 datetime.date(2020, 9, 16): 35,
 datetime.date(2020, 9, 17): 34,
 datetime.date(2020, 9, 18): 20,
 datetime.date(2020, 9, 19): 40,
 datetime.date(2020, 9, 20): 32,
 datetime.date(2020, 9, 21): 8,
 datetime.date(2020, 9, 22): 24,
 datetime.date(2020, 9, 23): 43,
 datetime.date(2020, 9, 24): 54,
 datetime.date(2020, 9, 25): 38,
 datetime.date(2020, 9, 26): 12,
 datetime.date(2020, 9, 27): 9,
 datetime.date(2020, 9, 28): 14,
 datetime.date(2020, 9, 29): 51,
 datetime.date(2020, 9, 30): 27,
 datetime.date(2020, 10, 1): 4,
 datetime.date(2020, 10, 2): 28,
 datetime.date(2020, 10, 3): 15,
 datetime.date(2020, 10, 4): 19,
 datetime.date(2020, 10, 5): 32,
 datetime.date(2020, 10, 6): 45,
 datetime.date(2020, 10, 7): 25,
 datetime.date(2020, 10, 8): 39,
 datetime.date(2020, 10, 9): 15,
 datetime.date(2020, 10, 10): 22,
 datetime.date(2020, 10, 11): 22,
 datetime.date(2020, 10, 12): 18,
 datetime.date(2020, 10, 13): 55,
 datetime.date(2020, 10, 14): 57,
 datetime.date(2020, 10, 15): 16,
 datetime.date(2020, 10, 16): 19,
 datetime.date(2020, 10, 17): 26,
 datetime.date(2020, 10, 18): 31,
 datetime.date(2020, 10, 19): 12,
 datetime.date(2020, 10, 20): 40,
 datetime.date(2020, 10, 21): 39,
 datetime.date(2020, 10, 22): 20,
 datetime.date(2020, 10, 23): 9,
 datetime.date(2020, 10, 24): 11,
 datetime.date(2020, 10, 25): 3,
 datetime.date(2020, 10, 26): 10,
 datetime.date(2020, 10, 27): 30,
 datetime.date(2020, 10, 28): 24,
 datetime.date(2020, 10, 29): 33,
 datetime.date(2020, 10, 30): 9,
 datetime.date(2020, 10, 31): 15,
 datetime.date(2020, 11, 1): 8,
 datetime.date(2020, 11, 2): 17,
 datetime.date(2020, 11, 3): 14,
 datetime.date(2020, 11, 4): 13,
 datetime.date(2020, 11, 5): 2,
 datetime.date(2020, 11, 6): 8,
 datetime.date(2020, 11, 7): 24,
 datetime.date(2020, 11, 8): 8,
 datetime.date(2020, 11, 9): 20,
 datetime.date(2020, 11, 10): 9,
 datetime.date(2020, 11, 11): 2,
 datetime.date(2020, 11, 12): 32,
 datetime.date(2020, 11, 13): 25,
 datetime.date(2020, 11, 14): 32,
 datetime.date(2020, 11, 15): 18,
 datetime.date(2020, 11, 16): 15,
 datetime.date(2020, 11, 17): 25,
 datetime.date(2020, 11, 18): 14,
 datetime.date(2020, 11, 19): 11,
 datetime.date(2020, 11, 20): 6,
 datetime.date(2020, 11, 21): 10,
 datetime.date(2020, 11, 22): 42,
 datetime.date(2020, 11, 23): 35,
 datetime.date(2020, 11, 24): 14,
 datetime.date(2020, 11, 25): 17,
 datetime.date(2020, 11, 26): 8,
 datetime.date(2020, 11, 27): 30,
 datetime.date(2020, 11, 28): 15,
 datetime.date(2020, 11, 29): 62,
 datetime.date(2020, 11, 30): 47,
 datetime.date(2020, 12, 1): 40,
 datetime.date(2020, 12, 2): 25,
 datetime.date(2020, 12, 3): 9,
 datetime.date(2020, 12, 4): 9,
 datetime.date(2020, 12, 5): 36,
 datetime.date(2020, 12, 6): 22,
 datetime.date(2020, 12, 7): 32,
 datetime.date(2020, 12, 8): 32,
 datetime.date(2020, 12, 9): 21,
 datetime.date(2020, 12, 10): 5,
 datetime.date(2020, 12, 11): 3,
 datetime.date(2020, 12, 12): 7,
 datetime.date(2020, 12, 13): 28,
 datetime.date(2020, 12, 14): 27,
 datetime.date(2020, 12, 15): 37,
 datetime.date(2020, 12, 16): 13,
 datetime.date(2020, 12, 17): 34,
 datetime.date(2020, 12, 18): 20,
 datetime.date(2020, 12, 19): 18,
 datetime.date(2020, 12, 20): 25,
 datetime.date(2020, 12, 21): 28,
 datetime.date(2020, 12, 22): 8,
 datetime.date(2020, 12, 23): 7,
 datetime.date(2020, 12, 24): 19,
 datetime.date(2020, 12, 25): 12,
 datetime.date(2020, 12, 26): 5,
 datetime.date(2020, 12, 27): 10,
 datetime.date(2020, 12, 28): 7,
 datetime.date(2020, 12, 29): 13,
 datetime.date(2020, 12, 30): 18,
 datetime.date(2020, 12, 31): 15}

Yay that worked, time to run it on everything. To do this, I further separated the data into 2 separate folders.

COMMENTS:

In [39]:
from pathlib import Path

comments_path = Path("/Users/crystalzhao/Desktop/~WELLESLEY~/FALL_26/CS 315/week4-tasks-new/data/CLOY/comments")
comments = {}

for jsonl in comments_path.iterdir():
    if jsonl.is_file():  
        print(jsonl)
        with open (jsonl, 'r', encoding = 'utf-8') as f:
            for line in f:
                data = json.loads(line) # to make sure each json line is handled as a vector
                utc = data['created_utc']
                dt_utc = datetime.fromtimestamp(utc).date()
                comments[dt_utc] = comments.get(dt_utc, 0) + 1   # this checks if the key exists and returns 0 if missing, then add one

/Users/crystalzhao/Desktop/~WELLESLEY~/FALL_26/CS 315/week4-tasks-new/data/CLOY/comments/cloy_comments_2025.jsonl
/Users/crystalzhao/Desktop/~WELLESLEY~/FALL_26/CS 315/week4-tasks-new/data/CLOY/comments/cloy_comments_2023.jsonl
/Users/crystalzhao/Desktop/~WELLESLEY~/FALL_26/CS 315/week4-tasks-new/data/CLOY/comments/cloy_comments_2021.jsonl
/Users/crystalzhao/Desktop/~WELLESLEY~/FALL_26/CS 315/week4-tasks-new/data/CLOY/comments/cloy_comments_2026.jsonl
/Users/crystalzhao/Desktop/~WELLESLEY~/FALL_26/CS 315/week4-tasks-new/data/CLOY/comments/cloy_comments_2024.jsonl
/Users/crystalzhao/Desktop/~WELLESLEY~/FALL_26/CS 315/week4-tasks-new/data/CLOY/comments/cloy_comments_2019.jsonl
/Users/crystalzhao/Desktop/~WELLESLEY~/FALL_26/CS 315/week4-tasks-new/data/CLOY/comments/cloy_comments_2020.jsonl
/Users/crystalzhao/Desktop/~WELLESLEY~/FALL_26/CS 315/week4-tasks-new/data/CLOY/comments/cloy_comments_2022.jsonl

In [27]:
len(comments)

2040

In [38]:
comments

{datetime.date(2024, 12, 31): 21,
 datetime.date(2025, 1, 1): 9,
 datetime.date(2025, 1, 2): 26,
 datetime.date(2025, 1, 3): 25,
 datetime.date(2025, 1, 4): 17,
 datetime.date(2025, 1, 5): 21,
 datetime.date(2025, 1, 6): 37,
 datetime.date(2025, 1, 7): 11,
 datetime.date(2025, 1, 8): 8,
 datetime.date(2025, 1, 9): 20,
 datetime.date(2025, 1, 10): 16,
 datetime.date(2025, 1, 11): 19,
 datetime.date(2025, 1, 12): 4,
 datetime.date(2025, 1, 13): 17,
 datetime.date(2025, 1, 14): 41,
 datetime.date(2025, 1, 15): 22,
 datetime.date(2025, 1, 16): 13,
 datetime.date(2025, 1, 17): 36,
 datetime.date(2025, 1, 18): 11,
 datetime.date(2025, 1, 19): 9,
 datetime.date(2025, 1, 20): 4,
 datetime.date(2025, 1, 21): 2,
 datetime.date(2025, 1, 22): 10,
 datetime.date(2025, 1, 23): 32,
 datetime.date(2025, 1, 24): 8,
 datetime.date(2025, 1, 25): 17,
 datetime.date(2025, 1, 26): 54,
 datetime.date(2025, 1, 27): 40,
 datetime.date(2025, 1, 28): 50,
 datetime.date(2025, 1, 29): 21,
 datetime.date(2025, 1, 30): 42,
 datetime.date(2025, 1, 31): 20,
 datetime.date(2025, 2, 1): 9,
 datetime.date(2025, 2, 2): 10,
 datetime.date(2025, 2, 3): 15,
 datetime.date(2025, 2, 4): 9,
 datetime.date(2025, 2, 5): 5,
 datetime.date(2025, 2, 6): 3,
 datetime.date(2025, 2, 7): 10,
 datetime.date(2025, 2, 8): 26,
 datetime.date(2025, 2, 9): 22,
 datetime.date(2025, 2, 10): 11,
 datetime.date(2025, 2, 11): 7,
 datetime.date(2025, 2, 12): 20,
 datetime.date(2025, 2, 13): 11,
 datetime.date(2025, 2, 14): 29,
 datetime.date(2025, 2, 15): 49,
 datetime.date(2025, 2, 16): 68,
 datetime.date(2025, 2, 17): 34,
 datetime.date(2025, 2, 18): 30,
 datetime.date(2025, 2, 19): 12,
 datetime.date(2025, 2, 20): 1,
 datetime.date(2025, 2, 21): 3,
 datetime.date(2025, 2, 22): 16,
 datetime.date(2025, 2, 23): 37,
 datetime.date(2025, 2, 24): 9,
 datetime.date(2025, 2, 25): 15,
 datetime.date(2025, 2, 26): 11,
 datetime.date(2025, 2, 27): 21,
 datetime.date(2025, 2, 28): 6,
 datetime.date(2025, 3, 1): 7,
 datetime.date(2025, 3, 2): 39,
 datetime.date(2025, 3, 3): 16,
 datetime.date(2025, 3, 4): 6,
 datetime.date(2025, 3, 5): 11,
 datetime.date(2025, 3, 6): 5,
 datetime.date(2025, 3, 7): 2,
 datetime.date(2025, 3, 8): 5,
 datetime.date(2025, 3, 9): 1,
 datetime.date(2025, 3, 10): 9,
 datetime.date(2025, 3, 12): 2,
 datetime.date(2025, 3, 13): 40,
 datetime.date(2025, 3, 14): 19,
 datetime.date(2025, 3, 15): 5,
 datetime.date(2025, 3, 16): 16,
 datetime.date(2025, 3, 17): 11,
 datetime.date(2025, 3, 18): 8,
 datetime.date(2025, 3, 19): 7,
 datetime.date(2025, 3, 20): 14,
 datetime.date(2025, 3, 21): 4,
 datetime.date(2025, 3, 23): 8,
 datetime.date(2025, 3, 24): 29,
 datetime.date(2025, 3, 25): 8,
 datetime.date(2025, 3, 26): 9,
 datetime.date(2025, 3, 27): 1,
 datetime.date(2025, 3, 28): 2,
 datetime.date(2025, 3, 29): 4,
 datetime.date(2025, 3, 30): 1,
 datetime.date(2025, 3, 31): 7,
 datetime.date(2025, 4, 1): 3,
 datetime.date(2025, 4, 3): 4,
 datetime.date(2025, 4, 4): 2,
 datetime.date(2025, 4, 5): 15,
 datetime.date(2025, 4, 6): 24,
 datetime.date(2025, 4, 7): 16,
 datetime.date(2025, 4, 8): 17,
 datetime.date(2025, 4, 9): 3,
 datetime.date(2025, 4, 10): 2,
 datetime.date(2025, 4, 11): 1,
 datetime.date(2025, 4, 12): 11,
 datetime.date(2025, 4, 13): 3,
 datetime.date(2025, 4, 14): 12,
 datetime.date(2025, 4, 15): 10,
 datetime.date(2025, 4, 16): 5,
 datetime.date(2025, 4, 17): 12,
 datetime.date(2025, 4, 18): 5,
 datetime.date(2025, 4, 19): 3,
 datetime.date(2025, 4, 20): 3,
 datetime.date(2025, 4, 23): 3,
 datetime.date(2025, 4, 24): 1,
 datetime.date(2025, 4, 25): 3,
 datetime.date(2025, 4, 26): 3,
 datetime.date(2025, 4, 27): 5,
 datetime.date(2025, 4, 28): 7,
 datetime.date(2025, 4, 30): 50,
 datetime.date(2025, 5, 1): 54,
 datetime.date(2025, 5, 2): 9,
 datetime.date(2025, 5, 3): 6,
 datetime.date(2025, 5, 4): 5,
 datetime.date(2025, 5, 5): 4,
 datetime.date(2025, 5, 6): 11,
 datetime.date(2025, 5, 7): 4,
 datetime.date(2025, 5, 8): 3,
 datetime.date(2025, 5, 10): 1,
 datetime.date(2025, 5, 11): 6,
 datetime.date(2025, 5, 12): 2,
 datetime.date(2025, 5, 13): 16,
 datetime.date(2025, 5, 14): 6,
 datetime.date(2025, 5, 15): 4,
 datetime.date(2025, 5, 16): 1,
 datetime.date(2025, 5, 18): 10,
 datetime.date(2025, 5, 19): 7,
 datetime.date(2025, 5, 20): 18,
 datetime.date(2025, 5, 21): 21,
 datetime.date(2025, 5, 22): 23,
 datetime.date(2025, 5, 23): 11,
 datetime.date(2025, 5, 24): 7,
 datetime.date(2025, 5, 25): 2,
 datetime.date(2025, 5, 27): 4,
 datetime.date(2025, 5, 28): 1,
 datetime.date(2025, 5, 29): 1,
 datetime.date(2025, 5, 30): 1,
 datetime.date(2025, 5, 31): 1,
 datetime.date(2025, 6, 1): 1,
 datetime.date(2025, 6, 2): 5,
 datetime.date(2025, 6, 3): 13,
 datetime.date(2025, 6, 4): 2,
 datetime.date(2025, 6, 5): 1,
 datetime.date(2025, 6, 6): 17,
 datetime.date(2025, 6, 7): 11,
 datetime.date(2025, 6, 8): 8,
 datetime.date(2025, 6, 9): 2,
 datetime.date(2025, 6, 10): 1,
 datetime.date(2025, 6, 11): 4,
 datetime.date(2025, 6, 15): 4,
 datetime.date(2025, 6, 16): 2,
 datetime.date(2025, 6, 17): 1,
 datetime.date(2025, 6, 18): 2,
 datetime.date(2025, 6, 19): 4,
 datetime.date(2025, 6, 20): 44,
 datetime.date(2025, 6, 21): 18,
 datetime.date(2025, 6, 22): 8,
 datetime.date(2025, 6, 23): 12,
 datetime.date(2025, 6, 24): 2,
 datetime.date(2025, 6, 25): 13,
 datetime.date(2025, 6, 26): 6,
 datetime.date(2025, 6, 27): 1,
 datetime.date(2025, 6, 28): 5,
 datetime.date(2025, 6, 29): 3,
 datetime.date(2025, 7, 3): 3,
 datetime.date(2025, 7, 5): 13,
 datetime.date(2025, 7, 6): 19,
 datetime.date(2025, 7, 7): 9,
 datetime.date(2025, 7, 8): 13,
 datetime.date(2025, 7, 9): 5,
 datetime.date(2025, 7, 10): 4,
 datetime.date(2025, 7, 11): 2,
 datetime.date(2025, 7, 13): 1,
 datetime.date(2025, 7, 14): 2,
 datetime.date(2025, 7, 15): 1,
 datetime.date(2025, 7, 17): 13,
 datetime.date(2025, 7, 18): 2,
 datetime.date(2025, 7, 19): 3,
 datetime.date(2025, 7, 20): 14,
 datetime.date(2025, 7, 21): 8,
 datetime.date(2025, 7, 22): 5,
 datetime.date(2025, 7, 23): 9,
 datetime.date(2025, 7, 24): 14,
 datetime.date(2025, 7, 25): 7,
 datetime.date(2025, 7, 26): 2,
 datetime.date(2025, 7, 27): 7,
 datetime.date(2025, 7, 28): 18,
 datetime.date(2025, 7, 29): 10,
 datetime.date(2025, 7, 30): 6,
 datetime.date(2025, 7, 31): 5,
 datetime.date(2025, 8, 2): 6,
 datetime.date(2025, 8, 3): 2,
 datetime.date(2025, 8, 4): 11,
 datetime.date(2025, 8, 5): 3,
 datetime.date(2025, 8, 6): 41,
 datetime.date(2025, 8, 7): 36,
 datetime.date(2025, 8, 8): 11,
 datetime.date(2025, 8, 9): 7,
 datetime.date(2025, 8, 10): 4,
 datetime.date(2025, 8, 11): 5,
 datetime.date(2025, 8, 12): 21,
 datetime.date(2025, 8, 13): 14,
 datetime.date(2025, 8, 14): 11,
 datetime.date(2025, 8, 15): 9,
 datetime.date(2025, 8, 17): 1,
 datetime.date(2025, 8, 18): 11,
 datetime.date(2025, 8, 19): 15,
 datetime.date(2025, 8, 20): 3,
 datetime.date(2025, 8, 22): 7,
 datetime.date(2025, 8, 23): 13,
 datetime.date(2025, 8, 24): 2,
 datetime.date(2025, 8, 25): 4,
 datetime.date(2025, 8, 26): 22,
 datetime.date(2025, 8, 27): 11,
 datetime.date(2025, 8, 28): 19,
 datetime.date(2025, 8, 29): 32,
 datetime.date(2025, 8, 30): 12,
 datetime.date(2025, 8, 31): 7,
 datetime.date(2025, 9, 1): 18,
 datetime.date(2025, 9, 2): 8,
 datetime.date(2025, 9, 3): 26,
 datetime.date(2025, 9, 4): 14,
 datetime.date(2025, 9, 5): 9,
 datetime.date(2025, 9, 6): 12,
 datetime.date(2025, 9, 7): 2,
 datetime.date(2025, 9, 8): 5,
 datetime.date(2025, 9, 9): 1,
 datetime.date(2025, 9, 10): 3,
 datetime.date(2025, 9, 11): 2,
 datetime.date(2025, 9, 12): 2,
 datetime.date(2025, 9, 13): 4,
 datetime.date(2025, 9, 14): 3,
 datetime.date(2025, 9, 15): 2,
 datetime.date(2025, 9, 16): 1,
 datetime.date(2025, 9, 17): 1,
 datetime.date(2025, 9, 18): 1,
 datetime.date(2025, 9, 19): 3,
 datetime.date(2025, 9, 20): 5,
 datetime.date(2025, 9, 21): 5,
 datetime.date(2025, 9, 22): 4,
 datetime.date(2025, 9, 23): 20,
 datetime.date(2025, 9, 24): 20,
 datetime.date(2025, 9, 25): 14,
 datetime.date(2025, 9, 26): 13,
 datetime.date(2025, 9, 27): 30,
 datetime.date(2025, 9, 28): 36,
 datetime.date(2025, 9, 29): 2,
 datetime.date(2025, 10, 1): 5,
 datetime.date(2025, 10, 2): 1,
 datetime.date(2025, 10, 3): 2,
 datetime.date(2025, 10, 4): 1,
 datetime.date(2025, 10, 5): 3,
 datetime.date(2025, 10, 7): 3,
 datetime.date(2025, 10, 9): 3,
 datetime.date(2025, 10, 10): 3,
 datetime.date(2025, 10, 11): 9,
 datetime.date(2025, 10, 12): 7,
 datetime.date(2025, 10, 13): 6,
 datetime.date(2025, 10, 14): 4,
 datetime.date(2025, 10, 15): 14,
 datetime.date(2025, 10, 16): 3,
 datetime.date(2025, 10, 17): 15,
 datetime.date(2025, 10, 18): 3,
 datetime.date(2025, 10, 19): 17,
 datetime.date(2025, 10, 20): 4,
 datetime.date(2025, 10, 21): 5,
 datetime.date(2025, 10, 22): 40,
 datetime.date(2025, 10, 23): 2,
 datetime.date(2025, 10, 24): 7,
 datetime.date(2025, 10, 25): 7,
 datetime.date(2025, 10, 26): 50,
 datetime.date(2025, 10, 27): 2,
 datetime.date(2025, 10, 28): 5,
 datetime.date(2025, 10, 29): 2,
 datetime.date(2025, 10, 31): 2,
 datetime.date(2025, 11, 1): 1,
 datetime.date(2025, 11, 2): 1,
 datetime.date(2025, 11, 5): 1,
 datetime.date(2025, 11, 6): 3,
 datetime.date(2025, 11, 7): 10,
 datetime.date(2025, 11, 8): 4,
 datetime.date(2025, 11, 9): 5,
 datetime.date(2025, 11, 10): 12,
 datetime.date(2025, 11, 11): 32,
 datetime.date(2025, 11, 12): 7,
 datetime.date(2025, 11, 13): 7,
 datetime.date(2025, 11, 14): 1,
 datetime.date(2025, 11, 15): 3,
 datetime.date(2025, 11, 16): 10,
 datetime.date(2025, 11, 17): 3,
 datetime.date(2025, 11, 18): 4,
 datetime.date(2025, 11, 19): 23,
 datetime.date(2025, 11, 20): 11,
 datetime.date(2025, 11, 21): 13,
 datetime.date(2025, 11, 22): 12,
 datetime.date(2025, 11, 23): 4,
 datetime.date(2025, 11, 24): 3,
 datetime.date(2025, 11, 25): 6,
 datetime.date(2025, 11, 26): 16,
 datetime.date(2025, 11, 27): 12,
 datetime.date(2025, 11, 28): 4,
 datetime.date(2025, 11, 29): 2,
 datetime.date(2025, 11, 30): 18,
 datetime.date(2025, 12, 1): 9,
 datetime.date(2025, 12, 2): 6,
 datetime.date(2025, 12, 3): 1,
 datetime.date(2025, 12, 4): 5,
 datetime.date(2025, 12, 5): 3,
 datetime.date(2025, 12, 6): 5,
 datetime.date(2025, 12, 7): 2,
 datetime.date(2025, 12, 8): 2,
 datetime.date(2025, 12, 9): 4,
 datetime.date(2025, 12, 10): 6,
 datetime.date(2025, 12, 11): 3,
 datetime.date(2025, 12, 12): 2,
 datetime.date(2025, 12, 13): 3,
 datetime.date(2025, 12, 14): 20,
 datetime.date(2025, 12, 15): 11,
 datetime.date(2025, 12, 16): 39,
 datetime.date(2025, 12, 17): 46,
 datetime.date(2025, 12, 18): 21,
 datetime.date(2025, 12, 19): 17,
 datetime.date(2025, 12, 20): 6,
 datetime.date(2025, 12, 21): 20,
 datetime.date(2025, 12, 22): 5,
 datetime.date(2025, 12, 23): 2,
 datetime.date(2025, 12, 24): 3,
 datetime.date(2025, 12, 25): 6,
 datetime.date(2025, 12, 26): 17,
 datetime.date(2025, 12, 27): 19,
 datetime.date(2025, 12, 28): 15,
 datetime.date(2025, 12, 29): 7,
 datetime.date(2025, 12, 30): 17,
 datetime.date(2025, 12, 31): 18,
 datetime.date(2023, 1, 2): 4,
 datetime.date(2023, 1, 3): 3,
 datetime.date(2023, 1, 4): 3,
 datetime.date(2023, 1, 7): 1,
 datetime.date(2023, 1, 8): 1,
 datetime.date(2023, 1, 11): 8,
 datetime.date(2023, 1, 12): 35,
 datetime.date(2023, 1, 13): 7,
 datetime.date(2023, 1, 15): 1,
 datetime.date(2023, 1, 17): 1,
 datetime.date(2023, 1, 18): 11,
 datetime.date(2023, 1, 19): 1,
 datetime.date(2023, 1, 20): 3,
 datetime.date(2023, 1, 22): 6,
 datetime.date(2023, 1, 23): 4,
 datetime.date(2023, 1, 24): 1,
 datetime.date(2023, 1, 27): 2,
 datetime.date(2023, 1, 29): 5,
 datetime.date(2023, 1, 30): 4,
 datetime.date(2023, 1, 31): 3,
 datetime.date(2023, 2, 1): 6,
 datetime.date(2023, 2, 2): 6,
 datetime.date(2023, 2, 3): 4,
 datetime.date(2023, 2, 4): 8,
 datetime.date(2023, 2, 5): 2,
 datetime.date(2023, 2, 6): 16,
 datetime.date(2023, 2, 7): 5,
 datetime.date(2023, 2, 10): 6,
 datetime.date(2023, 2, 11): 1,
 datetime.date(2023, 2, 12): 3,
 datetime.date(2023, 2, 14): 3,
 datetime.date(2023, 2, 15): 26,
 datetime.date(2023, 2, 16): 3,
 datetime.date(2023, 2, 17): 2,
 datetime.date(2023, 2, 18): 3,
 datetime.date(2023, 2, 19): 6,
 datetime.date(2023, 2, 20): 1,
 datetime.date(2023, 2, 21): 10,
 datetime.date(2023, 2, 22): 12,
 datetime.date(2023, 2, 23): 3,
 datetime.date(2023, 2, 24): 2,
 datetime.date(2023, 2, 26): 4,
 datetime.date(2023, 2, 27): 4,
 datetime.date(2023, 2, 28): 1,
 datetime.date(2023, 3, 1): 1,
 datetime.date(2023, 3, 2): 7,
 datetime.date(2023, 3, 3): 4,
 datetime.date(2023, 3, 4): 9,
 datetime.date(2023, 3, 5): 18,
 datetime.date(2023, 3, 6): 6,
 datetime.date(2023, 3, 7): 8,
 datetime.date(2023, 3, 9): 5,
 datetime.date(2023, 3, 10): 11,
 datetime.date(2023, 3, 11): 4,
 datetime.date(2023, 3, 12): 10,
 datetime.date(2023, 3, 13): 4,
 datetime.date(2023, 3, 14): 21,
 datetime.date(2023, 3, 15): 15,
 datetime.date(2023, 3, 16): 5,
 datetime.date(2023, 3, 17): 4,
 datetime.date(2023, 3, 18): 57,
 datetime.date(2023, 3, 19): 12,
 datetime.date(2023, 3, 20): 7,
 datetime.date(2023, 3, 21): 4,
 datetime.date(2023, 3, 22): 2,
 datetime.date(2023, 3, 23): 29,
 datetime.date(2023, 3, 24): 10,
 datetime.date(2023, 3, 25): 12,
 datetime.date(2023, 3, 26): 28,
 datetime.date(2023, 3, 27): 3,
 datetime.date(2023, 3, 28): 3,
 datetime.date(2023, 3, 29): 7,
 datetime.date(2023, 3, 30): 25,
 datetime.date(2023, 3, 31): 16,
 datetime.date(2023, 4, 1): 7,
 datetime.date(2023, 4, 2): 4,
 datetime.date(2023, 4, 3): 14,
 datetime.date(2023, 4, 4): 10,
 datetime.date(2023, 4, 5): 5,
 datetime.date(2023, 4, 6): 8,
 datetime.date(2023, 4, 7): 3,
 datetime.date(2023, 4, 8): 10,
 datetime.date(2023, 4, 9): 4,
 datetime.date(2023, 4, 10): 10,
 datetime.date(2023, 4, 11): 9,
 datetime.date(2023, 4, 12): 44,
 datetime.date(2023, 4, 13): 20,
 datetime.date(2023, 4, 14): 3,
 datetime.date(2023, 4, 15): 4,
 datetime.date(2023, 4, 16): 14,
 datetime.date(2023, 4, 17): 12,
 datetime.date(2023, 4, 18): 2,
 datetime.date(2023, 4, 19): 5,
 datetime.date(2023, 4, 20): 5,
 datetime.date(2023, 4, 21): 45,
 datetime.date(2023, 4, 22): 6,
 datetime.date(2023, 4, 23): 12,
 datetime.date(2023, 4, 24): 22,
 datetime.date(2023, 4, 25): 20,
 datetime.date(2023, 4, 26): 8,
 datetime.date(2023, 4, 27): 18,
 datetime.date(2023, 4, 28): 6,
 datetime.date(2023, 4, 29): 9,
 datetime.date(2023, 4, 30): 5,
 datetime.date(2023, 5, 1): 7,
 datetime.date(2023, 5, 4): 6,
 datetime.date(2023, 5, 5): 7,
 datetime.date(2023, 5, 6): 5,
 datetime.date(2023, 5, 7): 7,
 datetime.date(2023, 5, 8): 7,
 datetime.date(2023, 5, 9): 7,
 datetime.date(2023, 5, 10): 5,
 datetime.date(2023, 5, 11): 8,
 datetime.date(2023, 5, 12): 29,
 datetime.date(2023, 5, 13): 44,
 datetime.date(2023, 5, 14): 7,
 datetime.date(2023, 5, 15): 4,
 datetime.date(2023, 5, 16): 27,
 datetime.date(2023, 5, 17): 15,
 datetime.date(2023, 5, 18): 2,
 datetime.date(2023, 5, 19): 1,
 datetime.date(2023, 5, 20): 31,
 datetime.date(2023, 5, 21): 7,
 datetime.date(2023, 5, 22): 6,
 datetime.date(2023, 5, 23): 3,
 datetime.date(2023, 5, 24): 4,
 datetime.date(2023, 5, 25): 8,
 datetime.date(2023, 5, 26): 4,
 datetime.date(2023, 5, 27): 2,
 datetime.date(2023, 5, 28): 3,
 datetime.date(2023, 5, 30): 4,
 datetime.date(2023, 5, 31): 13,
 datetime.date(2023, 6, 1): 6,
 datetime.date(2023, 6, 2): 9,
 datetime.date(2023, 6, 3): 2,
 datetime.date(2023, 6, 4): 1,
 datetime.date(2023, 6, 6): 1,
 datetime.date(2023, 6, 7): 11,
 datetime.date(2023, 6, 9): 1,
 datetime.date(2023, 6, 12): 5,
 datetime.date(2023, 6, 13): 7,
 datetime.date(2023, 6, 15): 1,
 datetime.date(2023, 6, 16): 3,
 datetime.date(2023, 6, 17): 3,
 datetime.date(2023, 6, 18): 1,
 datetime.date(2023, 6, 19): 3,
 datetime.date(2023, 6, 20): 7,
 datetime.date(2023, 6, 21): 2,
 datetime.date(2023, 6, 25): 13,
 datetime.date(2023, 6, 26): 2,
 datetime.date(2023, 6, 27): 2,
 datetime.date(2023, 6, 30): 5,
 datetime.date(2023, 7, 2): 3,
 datetime.date(2023, 7, 3): 1,
 datetime.date(2023, 7, 4): 5,
 datetime.date(2023, 7, 5): 2,
 datetime.date(2023, 7, 6): 7,
 datetime.date(2023, 7, 7): 2,
 datetime.date(2023, 7, 8): 2,
 datetime.date(2023, 7, 9): 2,
 datetime.date(2023, 7, 10): 7,
 datetime.date(2023, 7, 11): 6,
 datetime.date(2023, 7, 12): 8,
 datetime.date(2023, 7, 14): 1,
 datetime.date(2023, 7, 15): 22,
 datetime.date(2023, 7, 16): 24,
 datetime.date(2023, 7, 17): 14,
 datetime.date(2023, 7, 18): 3,
 datetime.date(2023, 7, 21): 1,
 datetime.date(2023, 7, 22): 1,
 datetime.date(2023, 7, 23): 1,
 datetime.date(2023, 7, 24): 3,
 datetime.date(2023, 7, 25): 16,
 datetime.date(2023, 7, 26): 7,
 datetime.date(2023, 7, 27): 15,
 datetime.date(2023, 7, 28): 8,
 datetime.date(2023, 7, 29): 3,
 datetime.date(2023, 7, 30): 14,
 datetime.date(2023, 7, 31): 9,
 datetime.date(2023, 8, 1): 5,
 datetime.date(2023, 8, 2): 11,
 datetime.date(2023, 8, 3): 17,
 datetime.date(2023, 8, 4): 17,
 datetime.date(2023, 8, 5): 6,
 datetime.date(2023, 8, 6): 8,
 datetime.date(2023, 8, 7): 1,
 datetime.date(2023, 8, 8): 4,
 datetime.date(2023, 8, 9): 5,
 datetime.date(2023, 8, 10): 37,
 datetime.date(2023, 8, 11): 11,
 datetime.date(2023, 8, 12): 5,
 datetime.date(2023, 8, 13): 3,
 datetime.date(2023, 8, 14): 5,
 datetime.date(2023, 8, 15): 1,
 datetime.date(2023, 8, 16): 9,
 datetime.date(2023, 8, 19): 5,
 datetime.date(2023, 8, 20): 8,
 datetime.date(2023, 8, 21): 1,
 datetime.date(2023, 8, 22): 1,
 datetime.date(2023, 8, 24): 1,
 datetime.date(2023, 8, 26): 8,
 datetime.date(2023, 8, 27): 5,
 datetime.date(2023, 8, 30): 14,
 datetime.date(2023, 8, 31): 9,
 datetime.date(2023, 9, 1): 3,
 datetime.date(2023, 9, 2): 2,
 datetime.date(2023, 9, 4): 3,
 datetime.date(2023, 9, 5): 1,
 datetime.date(2023, 9, 6): 2,
 datetime.date(2023, 9, 8): 2,
 datetime.date(2023, 9, 10): 6,
 datetime.date(2023, 9, 12): 8,
 datetime.date(2023, 9, 15): 1,
 datetime.date(2023, 9, 16): 2,
 datetime.date(2023, 9, 17): 2,
 datetime.date(2023, 9, 19): 2,
 datetime.date(2023, 9, 20): 5,
 datetime.date(2023, 9, 21): 9,
 datetime.date(2023, 9, 22): 36,
 datetime.date(2023, 9, 23): 8,
 datetime.date(2023, 9, 24): 20,
 datetime.date(2023, 9, 25): 10,
 datetime.date(2023, 9, 26): 3,
 datetime.date(2023, 9, 27): 2,
 datetime.date(2023, 9, 29): 2,
 datetime.date(2023, 10, 2): 1,
 datetime.date(2023, 10, 4): 16,
 datetime.date(2023, 10, 5): 8,
 datetime.date(2023, 10, 8): 3,
 datetime.date(2023, 10, 9): 1,
 datetime.date(2023, 10, 14): 9,
 datetime.date(2023, 10, 15): 17,
 datetime.date(2023, 10, 16): 4,
 datetime.date(2023, 10, 17): 1,
 datetime.date(2023, 10, 19): 2,
 datetime.date(2023, 10, 21): 2,
 datetime.date(2023, 11, 5): 1,
 datetime.date(2023, 11, 6): 7,
 datetime.date(2023, 11, 7): 3,
 datetime.date(2023, 11, 8): 3,
 datetime.date(2023, 11, 9): 3,
 datetime.date(2023, 11, 10): 3,
 datetime.date(2023, 11, 12): 29,
 datetime.date(2023, 11, 13): 54,
 datetime.date(2023, 11, 14): 22,
 datetime.date(2023, 11, 15): 31,
 datetime.date(2023, 11, 16): 27,
 datetime.date(2023, 11, 17): 18,
 datetime.date(2023, 11, 18): 14,
 datetime.date(2023, 11, 19): 21,
 datetime.date(2023, 11, 20): 2,
 datetime.date(2023, 11, 21): 5,
 datetime.date(2023, 11, 22): 1,
 datetime.date(2023, 11, 23): 7,
 datetime.date(2023, 11, 24): 7,
 datetime.date(2023, 11, 25): 6,
 datetime.date(2023, 11, 26): 1,
 datetime.date(2023, 11, 27): 2,
 datetime.date(2023, 11, 28): 7,
 datetime.date(2023, 11, 29): 20,
 datetime.date(2023, 11, 30): 5,
 datetime.date(2023, 12, 1): 4,
 datetime.date(2023, 12, 2): 2,
 datetime.date(2023, 12, 3): 2,
 datetime.date(2023, 12, 4): 5,
 datetime.date(2023, 12, 6): 1,
 datetime.date(2023, 12, 8): 2,
 datetime.date(2023, 12, 9): 20,
 datetime.date(2023, 12, 10): 5,
 datetime.date(2023, 12, 11): 11,
 datetime.date(2023, 12, 12): 4,
 datetime.date(2023, 12, 13): 3,
 datetime.date(2023, 12, 14): 8,
 datetime.date(2023, 12, 15): 7,
 datetime.date(2023, 12, 16): 2,
 datetime.date(2023, 12, 17): 1,
 datetime.date(2023, 12, 20): 1,
 datetime.date(2023, 12, 21): 1,
 datetime.date(2023, 12, 22): 11,
 datetime.date(2023, 12, 23): 8,

In [29]:
submissions_path = Path('/Users/crystalzhao/Desktop/~WELLESLEY~/FALL_26/CS 315/week4-tasks-new/data/CLOY/submissions')
submissions = {}

for jsonl in submissions_path.iterdir():
    if jsonl.is_file():  
        with open (jsonl, 'r', encoding = 'utf-8') as f:
            for line in f:
                data = json.loads(line) # to make sure each json line is handled as a vector
                utc = data['timestamp']
                dt_utc = datetime.fromtimestamp(utc).date()
                submissions[dt_utc] = submissions.get(dt_utc, 0) + 1   # this checks if the key exists and returns 0 if missing, then add one

In [31]:
len(submissions)

1400

In [37]:
submissions

{datetime.date(2025, 1, 1): 1,
 datetime.date(2025, 1, 2): 3,
 datetime.date(2025, 1, 3): 2,
 datetime.date(2025, 1, 4): 1,
 datetime.date(2025, 1, 5): 3,
 datetime.date(2025, 1, 6): 2,
 datetime.date(2025, 1, 8): 1,
 datetime.date(2025, 1, 9): 3,
 datetime.date(2025, 1, 10): 3,
 datetime.date(2025, 1, 11): 4,
 datetime.date(2025, 1, 12): 1,
 datetime.date(2025, 1, 13): 3,
 datetime.date(2025, 1, 14): 3,
 datetime.date(2025, 1, 15): 1,
 datetime.date(2025, 1, 16): 2,
 datetime.date(2025, 1, 17): 2,
 datetime.date(2025, 1, 18): 2,
 datetime.date(2025, 1, 19): 1,
 datetime.date(2025, 1, 20): 2,
 datetime.date(2025, 1, 21): 1,
 datetime.date(2025, 1, 22): 2,
 datetime.date(2025, 1, 25): 1,
 datetime.date(2025, 1, 26): 5,
 datetime.date(2025, 1, 27): 1,
 datetime.date(2025, 1, 28): 6,
 datetime.date(2025, 1, 29): 2,
 datetime.date(2025, 1, 30): 5,
 datetime.date(2025, 1, 31): 4,
 datetime.date(2025, 2, 1): 1,
 datetime.date(2025, 2, 2): 1,
 datetime.date(2025, 2, 3): 2,
 datetime.date(2025, 2, 4): 1,
 datetime.date(2025, 2, 7): 3,
 datetime.date(2025, 2, 8): 2,
 datetime.date(2025, 2, 9): 2,
 datetime.date(2025, 2, 12): 1,
 datetime.date(2025, 2, 13): 2,
 datetime.date(2025, 2, 14): 2,
 datetime.date(2025, 2, 15): 5,
 datetime.date(2025, 2, 16): 3,
 datetime.date(2025, 2, 17): 1,
 datetime.date(2025, 2, 18): 3,
 datetime.date(2025, 2, 19): 1,
 datetime.date(2025, 2, 22): 2,
 datetime.date(2025, 2, 23): 3,
 datetime.date(2025, 2, 24): 2,
 datetime.date(2025, 2, 26): 1,
 datetime.date(2025, 2, 27): 1,
 datetime.date(2025, 2, 28): 1,
 datetime.date(2025, 3, 1): 4,
 datetime.date(2025, 3, 2): 5,
 datetime.date(2025, 3, 3): 2,
 datetime.date(2025, 3, 4): 1,
 datetime.date(2025, 3, 5): 2,
 datetime.date(2025, 3, 11): 1,
 datetime.date(2025, 3, 13): 1,
 datetime.date(2025, 3, 16): 2,
 datetime.date(2025, 3, 17): 2,
 datetime.date(2025, 3, 18): 1,
 datetime.date(2025, 3, 19): 3,
 datetime.date(2025, 3, 20): 1,
 datetime.date(2025, 3, 23): 3,
 datetime.date(2025, 3, 24): 2,
 datetime.date(2025, 3, 25): 1,
 datetime.date(2025, 3, 26): 1,
 datetime.date(2025, 3, 28): 2,
 datetime.date(2025, 3, 31): 1,
 datetime.date(2025, 4, 2): 1,
 datetime.date(2025, 4, 3): 1,
 datetime.date(2025, 4, 4): 1,
 datetime.date(2025, 4, 5): 2,
 datetime.date(2025, 4, 6): 1,
 datetime.date(2025, 4, 7): 3,
 datetime.date(2025, 4, 9): 1,
 datetime.date(2025, 4, 12): 1,
 datetime.date(2025, 4, 14): 1,
 datetime.date(2025, 4, 16): 1,
 datetime.date(2025, 4, 17): 3,
 datetime.date(2025, 4, 18): 1,
 datetime.date(2025, 4, 19): 1,
 datetime.date(2025, 4, 20): 1,
 datetime.date(2025, 4, 23): 1,
 datetime.date(2025, 4, 25): 1,
 datetime.date(2025, 4, 27): 1,
 datetime.date(2025, 4, 28): 1,
 datetime.date(2025, 4, 30): 2,
 datetime.date(2025, 5, 3): 1,
 datetime.date(2025, 5, 6): 2,
 datetime.date(2025, 5, 7): 1,
 datetime.date(2025, 5, 10): 1,
 datetime.date(2025, 5, 11): 2,
 datetime.date(2025, 5, 13): 5,
 datetime.date(2025, 5, 16): 1,
 datetime.date(2025, 5, 18): 3,
 datetime.date(2025, 5, 19): 1,
 datetime.date(2025, 5, 21): 3,
 datetime.date(2025, 5, 22): 3,
 datetime.date(2025, 5, 23): 1,
 datetime.date(2025, 5, 24): 1,
 datetime.date(2025, 5, 26): 1,
 datetime.date(2025, 5, 29): 1,
 datetime.date(2025, 5, 30): 1,
 datetime.date(2025, 6, 2): 3,
 datetime.date(2025, 6, 3): 1,
 datetime.date(2025, 6, 4): 1,
 datetime.date(2025, 6, 6): 3,
 datetime.date(2025, 6, 7): 1,
 datetime.date(2025, 6, 11): 1,
 datetime.date(2025, 6, 15): 1,
 datetime.date(2025, 6, 16): 2,
 datetime.date(2025, 6, 19): 1,
 datetime.date(2025, 6, 20): 3,
 datetime.date(2025, 6, 23): 1,
 datetime.date(2025, 6, 25): 2,
 datetime.date(2025, 6, 28): 1,
 datetime.date(2025, 7, 2): 1,
 datetime.date(2025, 7, 3): 2,
 datetime.date(2025, 7, 5): 1,
 datetime.date(2025, 7, 6): 3,
 datetime.date(2025, 7, 7): 1,
 datetime.date(2025, 7, 8): 2,
 datetime.date(2025, 7, 11): 1,
 datetime.date(2025, 7, 12): 2,
 datetime.date(2025, 7, 14): 1,
 datetime.date(2025, 7, 17): 2,
 datetime.date(2025, 7, 20): 3,
 datetime.date(2025, 7, 22): 1,
 datetime.date(2025, 7, 23): 1,
 datetime.date(2025, 7, 24): 1,
 datetime.date(2025, 7, 27): 3,
 datetime.date(2025, 7, 28): 1,
 datetime.date(2025, 7, 29): 2,
 datetime.date(2025, 7, 30): 1,
 datetime.date(2025, 7, 31): 1,
 datetime.date(2025, 8, 1): 1,
 datetime.date(2025, 8, 3): 1,
 datetime.date(2025, 8, 6): 1,
 datetime.date(2025, 8, 8): 1,
 datetime.date(2025, 8, 9): 1,
 datetime.date(2025, 8, 11): 1,
 datetime.date(2025, 8, 12): 3,
 datetime.date(2025, 8, 14): 1,
 datetime.date(2025, 8, 15): 2,
 datetime.date(2025, 8, 17): 1,
 datetime.date(2025, 8, 18): 2,
 datetime.date(2025, 8, 19): 1,
 datetime.date(2025, 8, 21): 1,
 datetime.date(2025, 8, 22): 1,
 datetime.date(2025, 8, 23): 1,
 datetime.date(2025, 8, 24): 1,
 datetime.date(2025, 8, 25): 1,
 datetime.date(2025, 8, 26): 1,
 datetime.date(2025, 8, 28): 3,
 datetime.date(2025, 8, 29): 1,
 datetime.date(2025, 8, 30): 1,
 datetime.date(2025, 8, 31): 1,
 datetime.date(2025, 9, 1): 3,
 datetime.date(2025, 9, 3): 3,
 datetime.date(2025, 9, 4): 1,
 datetime.date(2025, 9, 6): 1,
 datetime.date(2025, 9, 8): 2,
 datetime.date(2025, 9, 13): 2,
 datetime.date(2025, 9, 14): 2,
 datetime.date(2025, 9, 15): 1,
 datetime.date(2025, 9, 16): 2,
 datetime.date(2025, 9, 19): 3,
 datetime.date(2025, 9, 21): 1,
 datetime.date(2025, 9, 22): 2,
 datetime.date(2025, 9, 23): 2,
 datetime.date(2025, 9, 24): 2,
 datetime.date(2025, 9, 25): 1,
 datetime.date(2025, 9, 26): 1,
 datetime.date(2025, 9, 27): 1,
 datetime.date(2025, 9, 28): 2,
 datetime.date(2025, 9, 29): 3,
 datetime.date(2025, 10, 2): 1,
 datetime.date(2025, 10, 5): 1,
 datetime.date(2025, 10, 10): 1,
 datetime.date(2025, 10, 11): 2,
 datetime.date(2025, 10, 14): 2,
 datetime.date(2025, 10, 15): 2,
 datetime.date(2025, 10, 17): 2,
 datetime.date(2025, 10, 18): 1,
 datetime.date(2025, 10, 21): 1,
 datetime.date(2025, 10, 22): 5,
 datetime.date(2025, 10, 24): 1,
 datetime.date(2025, 10, 25): 1,
 datetime.date(2025, 10, 26): 1,
 datetime.date(2025, 10, 28): 1,
 datetime.date(2025, 10, 31): 1,
 datetime.date(2025, 11, 3): 1,
 datetime.date(2025, 11, 7): 1,
 datetime.date(2025, 11, 8): 2,
 datetime.date(2025, 11, 9): 3,
 datetime.date(2025, 11, 10): 2,
 datetime.date(2025, 11, 11): 2,
 datetime.date(2025, 11, 12): 2,
 datetime.date(2025, 11, 15): 1,
 datetime.date(2025, 11, 17): 1,
 datetime.date(2025, 11, 19): 3,
 datetime.date(2025, 11, 21): 2,
 datetime.date(2025, 11, 25): 1,
 datetime.date(2025, 11, 28): 1,
 datetime.date(2025, 11, 30): 2,
 datetime.date(2025, 12, 1): 1,
 datetime.date(2025, 12, 2): 1,
 datetime.date(2025, 12, 3): 1,
 datetime.date(2025, 12, 7): 1,
 datetime.date(2025, 12, 8): 2,
 datetime.date(2025, 12, 10): 1,
 datetime.date(2025, 12, 13): 1,
 datetime.date(2025, 12, 14): 3,
 datetime.date(2025, 12, 16): 3,
 datetime.date(2025, 12, 17): 1,
 datetime.date(2025, 12, 19): 1,
 datetime.date(2025, 12, 20): 1,
 datetime.date(2025, 12, 21): 2,
 datetime.date(2025, 12, 23): 1,
 datetime.date(2025, 12, 24): 2,
 datetime.date(2025, 12, 26): 1,
 datetime.date(2025, 12, 27): 1,
 datetime.date(2025, 12, 28): 2,
 datetime.date(2025, 12, 29): 1,
 datetime.date(2025, 12, 30): 1,
 datetime.date(2025, 12, 31): 3,
 datetime.date(2023, 1, 2): 1,
 datetime.date(2023, 1, 11): 1,
 datetime.date(2023, 1, 12): 1,
 datetime.date(2023, 1, 16): 1,
 datetime.date(2023, 1, 17): 1,
 datetime.date(2023, 1, 18): 1,
 datetime.date(2023, 1, 20): 1,
 datetime.date(2023, 1, 22): 1,
 datetime.date(2023, 1, 28): 1,
 datetime.date(2023, 1, 29): 1,
 datetime.date(2023, 1, 30): 1,
 datetime.date(2023, 2, 2): 1,
 datetime.date(2023, 2, 4): 1,
 datetime.date(2023, 2, 5): 1,
 datetime.date(2023, 2, 6): 2,
 datetime.date(2023, 2, 10): 1,
 datetime.date(2023, 2, 14): 2,
 datetime.date(2023, 2, 15): 4,
 datetime.date(2023, 2, 19): 1,
 datetime.date(2023, 2, 21): 1,
 datetime.date(2023, 2, 26): 1,
 datetime.date(2023, 3, 1): 2,
 datetime.date(2023, 3, 3): 1,
 datetime.date(2023, 3, 5): 3,
 datetime.date(2023, 3, 6): 1,
 datetime.date(2023, 3, 9): 1,
 datetime.date(2023, 3, 10): 2,
 datetime.date(2023, 3, 11): 1,
 datetime.date(2023, 3, 14): 1,
 datetime.date(2023, 3, 17): 1,
 datetime.date(2023, 3, 18): 2,
 datetime.date(2023, 3, 20): 2,
 datetime.date(2023, 3, 22): 1,
 datetime.date(2023, 3, 23): 2,
 datetime.date(2023, 3, 25): 1,
 datetime.date(2023, 3, 28): 1,
 datetime.date(2023, 3, 29): 1,
 datetime.date(2023, 3, 30): 3,
 datetime.date(2023, 4, 1): 1,
 datetime.date(2023, 4, 2): 1,
 datetime.date(2023, 4, 3): 2,
 datetime.date(2023, 4, 5): 1,
 datetime.date(2023, 4, 6): 1,
 datetime.date(2023, 4, 8): 3,
 datetime.date(2023, 4, 9): 1,
 datetime.date(2023, 4, 11): 1,
 datetime.date(2023, 4, 12): 4,
 datetime.date(2023, 4, 13): 2,
 datetime.date(2023, 4, 15): 1,
 datetime.date(2023, 4, 16): 1,
 datetime.date(2023, 4, 21): 2,
 datetime.date(2023, 4, 23): 1,
 datetime.date(2023, 4, 24): 2,
 datetime.date(2023, 4, 25): 1,
 datetime.date(2023, 4, 26): 2,
 datetime.date(2023, 4, 27): 1,
 datetime.date(2023, 4, 28): 1,
 datetime.date(2023, 4, 29): 2,
 datetime.date(2023, 4, 30): 2,
 datetime.date(2023, 5, 1): 1,
 datetime.date(2023, 5, 2): 1,
 datetime.date(2023, 5, 3): 1,
 datetime.date(2023, 5, 4): 3,
 datetime.date(2023, 5, 5): 1,
 datetime.date(2023, 5, 6): 1,
 datetime.date(2023, 5, 7): 1,
 datetime.date(2023, 5, 8): 3,
 datetime.date(2023, 5, 9): 3,
 datetime.date(2023, 5, 11): 1,
 datetime.date(2023, 5, 12): 1,
 datetime.date(2023, 5, 13): 3,
 datetime.date(2023, 5, 15): 1,
 datetime.date(2023, 5, 16): 1,
 datetime.date(2023, 5, 18): 1,
 datetime.date(2023, 5, 20): 4,
 datetime.date(2023, 5, 21): 1,
 datetime.date(2023, 5, 22): 1,
 datetime.date(2023, 5, 24): 2,
 datetime.date(2023, 5, 25): 1,
 datetime.date(2023, 5, 27): 1,
 datetime.date(2023, 5, 29): 1,
 datetime.date(2023, 5, 30): 1,
 datetime.date(2023, 5, 31): 1,
 datetime.date(2023, 6, 1): 2,
 datetime.date(2023, 6, 5): 1,
 datetime.date(2023, 6, 6): 1,
 datetime.date(2023, 6, 12): 1,
 datetime.date(2023, 6, 16): 2,
 datetime.date(2023, 6, 19): 2,
 datetime.date(2023, 6, 25): 2,
 datetime.date(2023, 6, 30): 1,
 datetime.date(2023, 7, 2): 1,
 datetime.date(2023, 7, 4): 2,
 datetime.date(2023, 7, 6): 3,
 datetime.date(2023, 7, 9): 1,
 datetime.date(2023, 7, 10): 1,
 datetime.date(2023, 7, 15): 4,
 datetime.date(2023, 7, 16): 1,
 datetime.date(2023, 7, 17): 1,
 datetime.date(2023, 7, 19): 4,
 datetime.date(2023, 7, 24): 1,
 datetime.date(2023, 7, 25): 2,
 datetime.date(2023, 7, 26): 1,
 datetime.date(2023, 7, 27): 1,
 datetime.date(2023, 7, 30): 1,
 datetime.date(2023, 8, 3): 2,
 datetime.date(2023, 8, 5): 3,
 datetime.date(2023, 8, 10): 3,
 datetime.date(2023, 8, 15): 1,
 datetime.date(2023, 8, 20): 1,
 datetime.date(2023, 8, 22): 1,
 datetime.date(2023, 8, 26): 1,
 datetime.date(2023, 8, 30): 2,
 datetime.date(2023, 8, 31): 2,
 datetime.date(2023, 9, 4): 1,
 datetime.date(2023, 9, 21): 4,
 datetime.date(2023, 9, 22): 2,
 datetime.date(2023, 9, 23): 1,
 datetime.date(2023, 9, 24): 2,
 datetime.date(2023, 10, 4): 1,
 datetime.date(2023, 10, 9): 1,
 datetime.date(2023, 10, 13): 1,
 datetime.date(2023, 10, 14): 1,
 datetime.date(2023, 11, 1): 2,
 datetime.date(2023, 11, 6): 1,
 datetime.date(2023, 11, 8): 1,
 datetime.date(2023, 11, 12): 3,
 datetime.date(2023, 11, 13): 2,
 datetime.date(2023, 11, 14): 2,
 datetime.date(2023, 11, 15): 4,
 datetime.date(2023, 11, 17): 5,
 datetime.date(2023, 11, 19): 3,
 datetime.date(2023, 11, 23): 2,
 datetime.date(2023, 11, 24): 1,
 datetime.date(2023, 11, 26): 1,
 datetime.date(2023, 11, 27): 1,
 datetime.date(2023, 11, 28): 1,
 datetime.date(2023, 11, 29): 1,
 datetime.date(2023, 11, 30): 1,
 datetime.date(2023, 12, 4): 1,
 datetime.date(2023, 12, 9): 2,
 datetime.date(2023, 12, 10): 1,
 datetime.date(2023, 12, 11): 1,
 datetime.date(2023, 12, 13): 1,
 datetime.date(2023, 12, 14): 2,
 datetime.date(2023, 12, 22): 1,
 datetime.date(2023, 12, 23): 1,
 datetime.date(2023, 12, 25): 1,
 datetime.date(2023, 12, 26): 1,
 datetime.date(2023, 12, 27): 1,
 datetime.date(2023, 12, 29): 1,
 datetime.date(2020, 12, 31): 3,
 datetime.date(2021, 1, 1): 9,
 datetime.date(2021, 1, 2): 7,
 datetime.date(2021, 1, 3): 5,
 datetime.date(2021, 1, 4): 2,
 datetime.date(2021, 1, 5): 2,
 datetime.date(2021, 1, 6): 2,
 datetime.date(2021, 1, 7): 1,
 datetime.date(2021, 1, 8): 1,
 datetime.date(2021, 1, 9): 4,
 datetime.date(2021, 1, 10): 5,
 datetime.date(2021, 1, 11): 5,
 datetime.date(2021, 1, 13): 2,
 datetime.date(2021, 1, 14): 3,
 datetime.date(2021, 1, 15): 2,
 datetime.date(2021, 1, 16): 3,
 datetime.date(2021, 1, 17): 6,
 datetime.date(2021, 1, 18): 4,
 datetime.date(2021, 1, 19): 3,
 datetime.date(2021, 1, 20): 1,
 datetime.date(2021, 1, 21): 3,
 datetime.date(2021, 1, 22): 1,
 datetime.date(2021, 1, 23): 2,
 datetime.date(2021, 1, 24): 2,
 datetime.date(2021, 1, 25): 3,
 datetime.date(2021, 1, 26): 1,
 datetime.date(2021, 1, 27): 1,
 datetime.date(2021, 1, 28): 1,
 datetime.date(2021, 1, 30): 1,
 datetime.date(2021, 1, 31): 2,
 datetime.date(2021, 2, 1): 4,
 datetime.date(2021, 2, 2): 4,
 datetime.date(2021, 2, 3): 2,
 datetime.date(2021, 2, 4): 1,
 datetime.date(2021, 2, 5): 1,
 datetime.date(2021, 2, 6): 2,
 datetime.date(2021, 2, 7): 2,
 datetime.date(2021, 2, 8): 5,
 datetime.date(2021, 2, 10): 4,
 datetime.date(2021, 2, 12): 1,
 datetime.date(2021, 2, 13): 2,
 datetime.date(2021, 2, 14): 3,
 datetime.date(2021, 2, 15): 4,
 datetime.date(2021, 2, 16): 2,
 datetime.date(2021, 2, 17): 2,
 datetime.date(2021, 2, 19): 2,
 datetime.date(2021, 2, 20): 1,
 datetime.date(2021, 2, 21): 6,
 datetime.date(2021, 2, 23): 4,
 datetime.date(2021, 2, 24): 1,
 datetime.date(2021, 2, 25): 2,
 datetime.date(2021, 2, 26): 1,
 datetime.date(2021, 2, 27): 4,
 datetime.date(2021, 2, 28): 3,
 datetime.date(2021, 3, 1): 4,
 datetime.date(2021, 3, 3): 1,
 datetime.date(2021, 3, 4): 2,
 datetime.date(2021, 3, 5): 3,
 datetime.date(2021, 3, 6): 1,
 datetime.date(2021, 3, 7): 1,
 datetime.date(2021, 3, 8): 3,
 datetime.date(2021, 3, 9): 1,
 datetime.date(2021, 3, 10): 2,
 datetime.date(2021, 3, 11): 1,
 datetime.date(2021, 3, 12): 6,
 datetime.date(2021, 3, 13): 3,
 datetime.date(2021, 3, 14): 4,
 datetime.date(2021, 3, 15): 1,
 datetime.date(2021, 3, 16): 2,
 datetime.date(2021, 3, 17): 1,
 datetime.date(2021, 3, 18): 3,
 datetime.date(2021, 3, 19): 3,
 datetime.date(2021, 3, 20): 2,
 datetime.date(2021, 3, 21): 2,
 datetime.date(2021, 3, 22): 1,
 datetime.date(2021, 3, 24): 3,
 datetime.date(2021, 3, 25): 3,
 datetime.date(2021, 3, 27): 2,
 datetime.date(2021, 3, 28): 2,
 datetime.date(2021, 3, 29): 2,
 datetime.date(2021, 4, 1): 3,
 datetime.date(2021, 4, 2): 3,
 datetime.date(2021, 4, 4): 2,
 datetime.date(2021, 4, 5): 1,
 datetime.date(2021, 4, 6): 1,
 datetime.date(2021, 4, 7): 1,
 datetime.date(2021, 4, 8): 4,
 datetime.date(2021, 4, 11): 1,
 datetime.date(2021, 4, 12): 2,
 datetime.date(2021, 4, 14): 1,
 datetime.date(2021, 4, 15): 1,
 datetime.date(2021, 4, 16): 3,
 datetime.date(2021, 4, 17): 3,
 datetime.date(2021, 4, 18): 1,
 datetime.date(2021, 4, 20): 3,
 datetime.date(2021, 4, 21): 1,
 datetime.date(2021, 4, 22): 2,
 datetime.date(2021, 4, 24): 5,
 datetime.date(2021, 4, 25): 1,
 datetime.date(2021, 4, 26): 1,
 datetime.date(2021, 4, 27): 5,
 datetime.date(2021, 4, 28): 1,
 datetime.date(2021, 4, 29): 3,
 datetime.date(2021, 5, 1): 8,
 datetime.date(2021, 5, 2): 5,
 datetime.date(2021, 5, 3): 1,
 datetime.date(2021, 5, 5): 2,
 datetime.date(2021, 5, 7): 1,
 datetime.date(2021, 5, 8): 1,
 datetime.date(2021, 5, 9): 1,
 datetime.date(2021, 5, 10): 1,
 datetime.date(2021, 5, 11): 3,
 datetime.date(2021, 5, 12): 2,
 datetime.date(2021, 5, 13): 6,
 datetime.date(2021, 5, 14): 2,
 datetime.date(2021, 5, 15): 3,
 datetime.date(2021, 5, 16): 3,
 datetime.date(2021, 5, 17): 2,
 datetime.date(2021, 5, 18): 2,
 datetime.date(2021, 5, 19): 1,
 datetime.date(2021, 5, 20): 1,
 datetime.date(2021, 5, 22): 1,
 datetime.date(2021, 5, 23): 2,
 datetime.date(2021, 5, 24): 1,
 datetime.date(2021, 5, 25): 4,
 datetime.date(2021, 5, 26): 2,
 datetime.date(2021, 5, 28): 2,
 datetime.date(2021, 5, 29): 3,
 datetime.date(2021, 5, 30): 1,
 datetime.date(2021, 5, 31): 4,
 datetime.date(2021, 6, 1): 3,
 datetime.date(2021, 6, 2): 1,
 datetime.date(2021, 6, 3): 2,
 datetime.date(2021, 6, 4): 2,
 datetime.date(2021, 6, 5): 3,
 datetime.date(2021, 6, 6): 5,
 datetime.date(2021, 6, 7): 2,
 datetime.date(2021, 6, 8): 3,
 datetime.date(2021, 6, 9): 3,
 datetime.date(2021, 6, 10): 3,
 datetime.date(2021, 6, 11): 3,
 datetime.date(2021, 6, 12): 2,
 datetime.date(2021, 6, 13): 2,
 datetime.date(2021, 6, 14): 5,
 datetime.date(2021, 6, 16): 1,
 datetime.date(2021, 6, 17): 3,
 datetime.date(2021, 6, 18): 3,
 datetime.date(2021, 6, 19): 3,
 datetime.date(2021, 6, 20): 3,
 datetime.date(2021, 6, 21): 4,
 datetime.date(2021, 6, 22): 2,
 datetime.date(2021, 6, 23): 6,
 datetime.date(2021, 6, 24): 4,
 datetime.date(2021, 6, 26): 3,
 datetime.date(2021, 6, 27): 2,
 datetime.date(2021, 6, 28): 1,
 datetime.date(2021, 6, 29): 2,
 datetime.date(2021, 6, 30): 1,
 datetime.date(2021, 7, 1): 4,
 datetime.date(2021, 7, 2): 3,
 datetime.date(2021, 7, 3): 1,
 datetime.date(2021, 7, 4): 3,
 datetime.date(2021, 7, 5): 3,
 datetime.date(2021, 7, 6): 2,
 datetime.date(2021, 7, 7): 5,
 datetime.date(2021, 7, 8): 5,
 datetime.date(2021, 7, 9): 5,
 datetime.date(2021, 7, 10): 5,
 datetime.date(2021, 7, 11): 4,
 datetime.date(2021, 7, 12): 5,
 datetime.date(2021, 7, 13): 2,
 datetime.date(2021, 7, 14): 2,
 datetime.date(2021, 7, 15): 4,
 datetime.date(2021, 7, 16): 3,
 datetime.date(2021, 7, 17): 5,
 datetime.date(2021, 7, 18): 5,
 datetime.date(2021, 7, 20): 1,
 datetime.date(2021, 7, 21): 1,
 datetime.date(2021, 7, 22): 3,
 datetime.date(2021, 7, 23): 5,
 datetime.date(2021, 7, 24): 3,
 datetime.date(2021, 7, 25): 2,
 datetime.date(2021, 7, 26): 2,
 datetime.date(2021, 7, 27): 5,
 datetime.date(2021, 7, 28): 2,
 datetime.date(2021, 7, 29): 4,
 datetime.date(2021, 7, 30): 1,
 datetime.date(2021, 7, 31): 2,
 datetime.date(2021, 8, 1): 7,
 datetime.date(2021, 8, 2): 2,
 datetime.date(2021, 8, 3): 5,
 datetime.date(2021, 8, 4): 5,
 datetime.date(2021, 8, 5): 2,
 datetime.date(2021, 8, 6): 1,
 datetime.date(2021, 8, 7): 1,
 datetime.date(2021, 8, 8): 2,
 datetime.date(2021, 8, 9): 5,
 datetime.date(2021, 8, 10): 3,
 datetime.date(2021, 8, 11): 2,
 datetime.date(2021, 8, 12): 2,
 datetime.date(2021, 8, 14): 3,
 datetime.date(2021, 8, 15): 3,
 datetime.date(2021, 8, 17): 1,
 datetime.date(2021, 8, 19): 2,
 datetime.date(2021, 8, 20): 2,
 datetime.date(2021, 8, 21): 2,
 datetime.date(2021, 8, 22): 3,
 datetime.date(2021, 8, 23): 1,
 datetime.date(2021, 8, 24): 3,
 datetime.date(2021, 8, 25): 1,
 datetime.date(2021, 8, 26): 2,
 datetime.date(2021, 8, 27): 3,
 datetime.date(2021, 8, 28): 3,
 datetime.date(2021, 8, 29): 2,
 datetime.date(2021, 8, 30): 4,
 datetime.date(2021, 8, 31): 1,
 datetime.date(2021, 9, 1): 1,
 datetime.date(2021, 9, 2): 2,
 datetime.date(2021, 9, 4): 5,
 datetime.date(2021, 9, 6): 4,
 datetime.date(2021, 9, 7): 3,
 datetime.date(2021, 9, 8): 3,
 datetime.date(2021, 9, 10): 1,
 datetime.date(2021, 9, 11): 1,
 datetime.date(2021, 9, 12): 2,
 datetime.date(2021, 9, 13): 1,
 datetime.date(2021, 9, 14): 2,
 datetime.date(2021, 9, 15): 7,
 datetime.date(2021, 9, 16): 2,
 datetime.date(2021, 9, 17): 3,
 datetime.date(2021, 9, 18): 4,
 datetime.date(2021, 9, 19): 2,
 datetime.date(2021, 9, 20): 2,
 datetime.date(2021, 9, 21): 1,
 datetime.date(2021, 9, 22): 3,
 datetime.date(2021, 9, 23): 2,
 datetime.date(2021, 9, 24): 1,
 datetime.date(2021, 9, 27): 3,
 datetime.date(2021, 9, 28): 2,
 datetime.date(2021, 9, 30): 3,
 datetime.date(2021, 10, 1): 1,
 datetime.date(2021, 10, 2): 3,
 datetime.date(2021, 10, 3): 4,
 datetime.date(2021, 10, 4): 1,
 datetime.date(2021, 10, 5): 2,
 datetime.date(2021, 10, 6): 3,
 datetime.date(2021, 10, 8): 1,
 datetime.date(2021, 10, 9): 1,
 datetime.date(2021, 10, 10): 1,
 datetime.date(2021, 10, 11): 4,
 datetime.date(2021, 10, 12): 4,

## Creating DFs

In [32]:
comments_df = pd.DataFrame.from_dict(comments, orient='index')
submissions_df = pd.DataFrame.from_dict(submissions, orient='index')

In [33]:
comments_df.head()

             0
2024-12-31  21
2025-01-01   9
2025-01-02  26
2025-01-03  25
2025-01-04  17

In [36]:
full_df = pd.merge(comments_df, submissions_df, left_index=True, right_index=True)

In [35]:
full_df.head()

            0_x  0_y
2025-01-01    9    1
2025-01-02   26    3
2025-01-03   25    2
2025-01-04   17    1
2025-01-05   21    3

In [40]:
full_df = full_df.rename(columns={'0_x': 'comments-counts', '0_y': 'submissions-counts'})
full_df

            comments-counts  submissions-counts
2025-01-01                9                   1
2025-01-02               26                   3
2025-01-03               25                   2
2025-01-04               17                   1
2025-01-05               21                   3
...                     ...                 ...
2022-12-24               25                   1
2022-12-25               11                   3
2022-12-26               13                   5
2022-12-27               10                   1
2022-12-30               14                   3

[1375 rows x 2 columns]

Last thing, sort by index.

In [41]:
full_df = full_df.sort_index()
full_df.head()

            comments-counts  submissions-counts
2020-03-11                4                   1
2020-03-12                1                   1
2020-03-15                2                   1
2020-03-16                5                   2
2020-03-18               13                   1

Great!

## Plotting

In [42]:
import matplotlib